CREATE DATABASE IF4;

CREATE TABLE mahasiswa(
    NIM varchar(8) PRIMARY KEY,
    NAMA varchar(30),
    ALAMAT varchar(50)
);

CREATE TABLE matakuliah(
    KODEMK varchar(6) PRIMARY KEY,
    NAMAMK varchar(30),
    SKS varchar(1)
);

CREATE TABLE perwalian(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NIM varchar(8),
    KODEMK varchar(6),
    TAHUNAKADEMIK varchar(5)
);

INSERT INTO mahasiswa VALUES('10109001', 'RINA DEWI', 'JL.PAJAJARAN');
INSERT INTO mahasiswa VALUES('10109002', 'BUDIMAN', 'JL.KARAPITAN');
INSERT INTO mahasiswa VALUES('10109003', 'DEWI', 'JL.NANJUNG');
INSERT INTO mahasiswa VALUES('10109004', 'RIDWAN', 'JL.CIBEBER');

INSERT INTO matakuliah VALUES('IF1001', 'ALGORITMA', '3');
INSERT INTO matakuliah VALUES('IF1002', 'PANCASILA', '2');
INSERT INTO matakuliah VALUES('IF1003', 'KOMPUTER IT-1', '2');
INSERT INTO matakuliah VALUES('IF1004', 'MATEMATIKA', '3');

INSERT INTO perwalian(NIM, KODEMK, TAHUNAKADEMIK) VALUES('10109001', 'IF1001', '20181');
INSERT INTO perwalian(NIM, KODEMK, TAHUNAKADEMIK) VALUES('10109001', 'IF1002', '20181');
INSERT INTO perwalian(NIM, KODEMK, TAHUNAKADEMIK) VALUES('10109002', 'IF1002', '20181');
INSERT INTO perwalian(NIM, KODEMK, TAHUNAKADEMIK) VALUES('10109003', 'IF1001', '20181');

SELECT NAMA as NAMASISWA, NAMAMK as NAMAMATAKULIAH, SKS, TAHUNAKADEMIK as TAHUN from perwalian inner join mahasiswa on mahasiswa.NIM = perwalian.NIM inner join matakuliah on matakuliah.KODEMK = perwalian.KODEMK;

SELECT MAHASISWA.NAMA, MATAKULIAH.NAMAMK, MATAKULIAH.SKS, PERWALIAN.TAHUNAKADEMIK
FROM MAHASISWA, MATAKULIAH, PERWALIAN
WHERE MAHASISWA.NIM = PERWALIAN.NIM
AND MATAKULIAH.KODEMK = PERWALIAN.KODEMK
AND MAHASISWA.NAMA = "RINA DEWI";