/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan1.hanif.pbo.main;

import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    Mahasiswa mahasiswa;
    
    public MainView() {
        mahasiswa = new Mahasiswa();
        initComponents();
    }
    
    public JTextArea getAlamat() {
        return alamat;
    }

    public JRadioButton getBtnKelas1() {
        return btnKelas1;
    }

    public JRadioButton getBtnKelas2() {
        return btnKelas2;
    }

    public JRadioButton getBtnKelas3() {
        return btnKelas3;
    }

    public JRadioButton getBtnKelas4() {
        return btnKelas4;
    }

    public JComboBox<String> getJurusan() {
        return jurusan;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNim() {
        return txtNim;
    }

    public JTextArea getTxtTampil() {
        return txtTampil;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKelas = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        btnKelas4 = new javax.swing.JRadioButton();
        btnKelas1 = new javax.swing.JRadioButton();
        btnKelas2 = new javax.swing.JRadioButton();
        btnKelas3 = new javax.swing.JRadioButton();
        jurusan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        BtnTampil = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTampil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Mahasiswa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setName("mainPanel"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA MAHASISWA");
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 140));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jPanel4.setBackground(new java.awt.Color(238, 238, 238));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Data Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(238, 238, 238));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 580, 590));

        jLabel2.setText("ALAMAT                      :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 20));

        jLabel3.setText("NAMA MAHASISWA :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("NIM MAHASISWA     :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        jLabel5.setText("KELAS                       :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel6.setText("JURUSAN                 :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        txtNama.setBackground(new java.awt.Color(255, 255, 255));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel4.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 330, 40));

        txtNim.setBackground(new java.awt.Color(255, 255, 255));
        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });
        jPanel4.add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 330, 40));

        btnKelas4.setBackground(new java.awt.Color(238, 238, 238));
        buttonGroupKelas.add(btnKelas4);
        btnKelas4.setText("IF - 7");
        btnKelas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelas4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnKelas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        btnKelas1.setBackground(new java.awt.Color(238, 238, 238));
        buttonGroupKelas.add(btnKelas1);
        btnKelas1.setText("IF - 4");
        btnKelas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelas1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnKelas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        btnKelas2.setBackground(new java.awt.Color(238, 238, 238));
        buttonGroupKelas.add(btnKelas2);
        btnKelas2.setText("IF - 5");
        btnKelas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelas2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnKelas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        btnKelas3.setBackground(new java.awt.Color(238, 238, 238));
        buttonGroupKelas.add(btnKelas3);
        btnKelas3.setText("IF - 6");
        btnKelas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelas3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnKelas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jurusan.setBackground(new java.awt.Color(204, 204, 204));
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "SISTEM INFORMASI", "TEKNIK KOMPUTER" }));
        jPanel4.add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 240, 30));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 380, 100));

        BtnTampil.setBackground(new java.awt.Color(204, 204, 204));
        BtnTampil.setText("Tampil Data");
        BtnTampil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTampilMouseClicked(evt);
            }
        });
        jPanel4.add(BtnTampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 140, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 580, 590));

        jPanel5.setBackground(new java.awt.Color(238, 238, 238));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 590));

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tampil Data Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(238, 238, 238));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 580, 590));

        txtTampil.setBackground(new java.awt.Color(255, 255, 255));
        txtTampil.setColumns(20);
        txtTampil.setRows(5);
        jScrollPane2.setViewportView(txtTampil);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 520, 530));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 580, 590));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void btnKelas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelas4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelas4ActionPerformed

    private void btnKelas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelas1ActionPerformed

    private void btnKelas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelas2ActionPerformed

    private void btnKelas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelas3ActionPerformed

    private void BtnTampilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTampilMouseClicked
        // TODO add your handling code here:
        mahasiswa.tampilDataMahasiswa(this);
    }//GEN-LAST:event_BtnTampilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTampil;
    private javax.swing.JTextArea alamat;
    private javax.swing.JRadioButton btnKelas1;
    private javax.swing.JRadioButton btnKelas2;
    private javax.swing.JRadioButton btnKelas3;
    private javax.swing.JRadioButton btnKelas4;
    private javax.swing.ButtonGroup buttonGroupKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextArea txtTampil;
    // End of variables declaration//GEN-END:variables
}
