/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gararetech.cinemas.view;

//import javax.swing.ImageIcon;
import com.gararetech.cinemas.view.builder.PosterPacker;
import com.gararetech.cinemas.utils.ScaleImage;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author user
 */
public class DashboardView extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public DashboardView() {
        initComponents();

//        ImageIcon film1 = new ImageIcon(getClass().getResource("images/film1.jpg"));
//        ScaleImage scaleImg = new ScaleImage(film1, 250, 368);
//        ImageIcon resizeFilm1 = scaleImg.scaleImage();
//        
//        this.getPoster1().setIcon(resizeFilm1);
        
        getContentPanel().setBackground(Color.decode("#F281B00"));
        
        PosterPacker poster = new PosterPacker("images/film1.jpg", getContentPanel());
        poster.setGrid();
    }

    public JPanel getContentPanel() {
        return ContentPanel;
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel = new javax.swing.JPanel();
        contentScrollPanel = new javax.swing.JScrollPane();
        contentScrollPanel.getVerticalScrollBar().setUnitIncrement(16);
        ContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 615));
        setPreferredSize(new java.awt.Dimension(858, 615));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headPanel.setBackground(Color.decode("#1D1C1C"));

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(headPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1048, 90));

        contentScrollPanel.setBackground(new java.awt.Color(0, 0, 0));
        contentScrollPanel.setBorder(null);
        contentScrollPanel.setForeground(new java.awt.Color(255, 255, 255));
        contentScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        contentScrollPanel.setPreferredSize(new java.awt.Dimension(1063, 533));

        ContentPanel.setLayout(new java.awt.GridLayout(1, 0));
        contentScrollPanel.setViewportView(ContentPanel);

        getContentPane().add(contentScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JScrollPane contentScrollPanel;
    private javax.swing.JPanel headPanel;
    // End of variables declaration//GEN-END:variables

}
